##################################################################
#
# docker-compose.yml 需要和 Dockerfile 文件,在同一目录下.
#
# 官方参考文档:
#   - https://docs.docker.com/compose/gettingstarted/
#   - https://docs.docker.com/compose/rails/
#
# 常用命令:  (查看帮助: docker-compose --help)
#   - 启动:
#        - docker-compose up      # boot the app
#        - docker-compose up -d   # 后台运行
#   - 查看启动进程:
#        - docker-compose ps
#   - 其他:
#        - docker-compose build              # build the image
#        - docker-compose run web env
#        - docker-compose stop
#
#
##################################################################


cms_nginx:
  image: daocloud.io/library/nginx:1.11.5
  volumes:
    - /iDockerShare/cms_server:/tmp/
  links:
    - cms_server
  ports:
    - "8080:80"


# web服务器容器
cms_server:
  #build: ./build/qdfm_server/qdfm_prod/     # 指定 Dockerfile 文件的路径
  image: cmswing:0.3    # 指定IMAGE
  ports:
    - "0.0.0.0:8360:8360"
  volumes:
    - /iDockerShare/cms_server:/web/cmswing
  expose:
    - "8360"
  links:
    - cms_db
  command: node ./www/development.js


# mysql-db:
cms_db:
  image: daocloud.io/library/mysql:5.7
  volumes:
    - /iDockerShare/cms_db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=your_password
  ports:
    - "127.0.0.1:33060:3306"
  expose:
    - "3306"
    - "33060"



